trigger:
  - master

pool:
  name: Hosted Ubuntu 1604
  
steps:
- task: Docker@2
  displayName: 'Build and Push'
  inputs:
    containerRegistry: wastechain
    repository: 'wastechain-frontend'
    tags: |
     $(Build.BuildId)
     master