NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.third-party-organisation.org-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.third-party-organisation.org-cert.pem
    OrganizationalUnitIdentifier: peer
