version: '2'

services:
  api.ordering-organisation.com:
    container_name: api.ordering-organisation.com
    image: wastechain.azurecr.io/wastechain-api:master
    environment:
      - CHANNEL_NAME=wastechain
      - USERNAME=Admin@ordering-organisation.com
      - WALLET_LOCATION=/wallet/ordering-organisation
      - CONNECTION_FILE=/connection-profiles/ordering-connection.yaml
      - PORT=3000
      - FABRIC_NETWORK_URL=host.docker.internal
    ports:
      - 3000:3000
    volumes:
        - ./wallet:/wallet
        - ./connection-profiles:/connection-profiles

  api.subcontractor-organisation.com:
    container_name: api.subcontractor-organisation.com
    image: wastechain.azurecr.io/wastechain-api:master
    environment:
      - CHANNEL_NAME=wastechain
      - USERNAME=Admin@subcontractor-organisation.com
      - WALLET_LOCATION=/wallet/subcontractor-organisation
      - CONNECTION_FILE=/connection-profiles/subcontractor-connection.yaml
      - PORT=6000
      - FABRIC_NETWORK_URL=host.docker.internal
    ports:
      - 6000:6000
    volumes:
        - ./wallet:/wallet
        - ./connection-profiles:/connection-profiles