version: '2'

services:
  api.ordering-organisation.com:
    container_name: api.ordering-organisation.com
    image: wastechain.azurecr.io/wastechain-api:master
    environment:
      - CHANNEL_NAME=wastechain
      - USERNAME=Admin@ordering-organisation.com
      - WALLET_LOCATION=/wallet/ordering-organisation
      - CONNECTION_FILE=/connection-profiles/ordering-connection.yaml
      - PORT=3000
      - FABRIC_NETWORK_URL=host.docker.internal
      - ALLOW_CORS=true
    ports:
      - 3000:3000
    volumes:
        - ./wallet:/wallet
        - ./connection-profiles:/connection-profiles

  api.subcontractor-organisation.com:
    container_name: api.subcontractor-organisation.com
    image: wastechain.azurecr.io/wastechain-api:master
    environment:
      - CHANNEL_NAME=wastechain
      - USERNAME=Admin@subcontractor-organisation.com
      - WALLET_LOCATION=/wallet/subcontractor-organisation
      - CONNECTION_FILE=/connection-profiles/subcontractor-connection.yaml
      - PORT=6000
      - FABRIC_NETWORK_URL=host.docker.internal
      - ALLOW_CORS=true
    ports:
      - 6000:6000
    volumes:
        - ./wallet:/wallet
        - ./connection-profiles:/connection-profiles

  api.third-party-organisation.com:
    container_name: api.third-party-organisation.com
    image: wastechain.azurecr.io/wastechain-api:master
    environment:
      - CHANNEL_NAME=wastechain
      - USERNAME=Admin@third-party-organisation.com
      - WALLET_LOCATION=/wallet/third-party-organisation
      - CONNECTION_FILE=/connection-profiles/third-party-connection.yaml
      - PORT=9000
      - FABRIC_NETWORK_URL=host.docker.internal
      - ALLOW_CORS=true
    ports:
      - 9000:9000
    volumes:
        - ./wallet:/wallet
        - ./connection-profiles:/connection-profiles

### Frontend

  frontend.ordering-organisation.com:
    container_name: frontend.ordering-organisation.com
    image: wastechain.azurecr.io/wastechain-frontend:master
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    ports:
      - 8080:3000
    depends_on:
      - api.ordering-organisation.com

  frontend.subcontractor-organisation.com:
    container_name: frontend.subcontractor-organisation.com
    image: wastechain.azurecr.io/wastechain-frontend:master
    environment:
      - REACT_APP_API_URL=http://localhost:6000
    ports:
      - 10080:3000
    depends_on:
      - api.subcontractor-organisation.com

  frontend.third-party-organisation.com:
    container_name: frontend.third-party-organisation.com
    image: wastechain.azurecr.io/wastechain-frontend:master
    environment:
      - REACT_APP_API_URL=http://localhost:9000
    ports:
      - 12080:3000
    depends_on:
      - api.third-party-organisation.com