version: '2'

services:
  api.ordering-organisation.com:
    container_name: api.ordering-organisation.com
    build:
      dockerfile: Dockerfile
      context: ../application
    network_mode: "host"
    environment:
      - CHANNEL_NAME=wastechain
      - USERNAME=Admin@ordering-organisation.com
      - WALLET_LOCATION=/wallet/ordering-organisation
      - CONNECTION_FILE=/connection-profiles/ordering-connection.yaml
      - PORT=10000
      - FABRIC_NETWORK_URL=${FABRIC_NETWORK_URL}
      - ALLOW_CORS=true
    ports:
      - 10000:10000
    volumes:
        - ./wallet:/wallet
        - ./connection-profiles:/connection-profiles

  api.subcontractor-organisation.com:
    container_name: api.subcontractor-organisation.com
    build:
      dockerfile: Dockerfile
      context: ../application
    network_mode: "host"
    environment:
      - CHANNEL_NAME=wastechain
      - USERNAME=Admin@subcontractor-organisation.com
      - WALLET_LOCATION=/wallet/subcontractor-organisation
      - CONNECTION_FILE=/connection-profiles/subcontractor-connection.yaml
      - PORT=30000
      - FABRIC_NETWORK_URL=${FABRIC_NETWORK_URL}
      - ALLOW_CORS=true
    ports:
      - 30000:30000
    volumes:
        - ./wallet:/wallet
        - ./connection-profiles:/connection-profiles

  api.third-party-organisation.com:
    container_name: api.third-party-organisation.com
    build:
      dockerfile: Dockerfile
      context: ../application
    network_mode: "host"
    environment:
      - CHANNEL_NAME=wastechain
      - USERNAME=Admin@third-party-organisation.com
      - WALLET_LOCATION=/wallet/third-party-organisation
      - CONNECTION_FILE=/connection-profiles/third-party-connection.yaml
      - PORT=50000
      - FABRIC_NETWORK_URL=${FABRIC_NETWORK_URL}
      - ALLOW_CORS=true
    ports:
      - 50000:50000
    volumes:
        - ./wallet:/wallet
        - ./connection-profiles:/connection-profiles

### Frontend

  frontend.ordering-organisation.com:
    container_name: frontend.ordering-organisation.com
    build:
      dockerfile: Dockerfile
      context: ../frontend
      args:
        - REACT_APP_API_URL=http://${API_URL}:10000
    ports:
      - 8080:3000
    depends_on:
      - api.ordering-organisation.com

  frontend.subcontractor-organisation.com:
    container_name: frontend.subcontractor-organisation.com
    build:
      dockerfile: Dockerfile
      context: ../frontend
      args:
        - REACT_APP_API_URL=http://${API_URL}:30000
    ports:
      - 10080:3000
    depends_on:
      - api.subcontractor-organisation.com

  frontend.third-party-organisation.com:
    container_name: frontend.third-party-organisation.com
    build:
      dockerfile: Dockerfile
      context: ../frontend
      args:
        - REACT_APP_API_URL=http://${API_URL}:50000
    ports:
      - 12080:3000
    depends_on:
      - api.third-party-organisation.com
