---
Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/wastechain.org/msp

    - &OrderingOrg
        Name: OrderingOrgMSP
        ID: OrderingOrgMSP
        MSPDir: crypto-config/peerOrganizations/ordering-organisation.com/msp
        AnchorPeers:
            - Host: peer0.ordering-organisation.com
              Port: 7051

    - &SubcontractorOrg
        Name: SubcontractorOrgMSP
        ID: SubcontractorOrgMSP
        MSPDir: crypto-config/peerOrganizations/subcontractor-organisation.com/msp
        AnchorPeers:
            - Host: peer0.subcontractor-organisation.com
              Port: 7051

    - &ThirdPartyOrg
        Name: ThirdPartyOrgMSP
        ID: ThirdPartyOrgMSP
        MSPDir: crypto-config/peerOrganizations/third-party-organisation.org/msp
        AnchorPeers:
            - Host: peer0.third-party-organisation.org
              Port: 7051

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.wastechain.org:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:

Application: &ApplicationDefaults
    Organizations:

Capabilities:
    Global: &ChannelCapabilities
        V1_1: true

    Orderer: &OrdererCapabilities
        V1_1: true

    Application: &ApplicationCapabilities
        V1_1: true

Profiles:
    OrdererGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            WastechainConsortium:
                Organizations:
                    - *OrderingOrg
                    - *SubcontractorOrg
                    - *ThirdPartyOrg
    
    WastechainChannel:
        Consortium: WastechainConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *OrderingOrg
                - *SubcontractorOrg
                - *ThirdPartyOrg

            Capabilities:
                <<: *ApplicationCapabilities