# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: wastechain.org
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Ordering Organisation
  # ---------------------------------------------------------------------------
  - Name: OrderingOrg
    Domain: ordering-organisation.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Subcontractor Organisation
  # ---------------------------------------------------------------------------
  - Name: SubcontractorOrg
    Domain: subcontractor-organisation.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Third-Party Organisation
  # ---------------------------------------------------------------------------
  - Name: ThirdPartyOrg
    Domain: third-party-organisation.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1