NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.ordering-organisation.org-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.ordering-organisation.org-cert.pem
    OrganizationalUnitIdentifier: peer
