Vagrant.require_version ">= 1.7.4"
Vagrant.configure('2') do |config|
  config.vm.box = "generic/debian9"

  config.vm.network :forwarded_port, guest: 7050, host: 7050, id: "orderer", host_ip: "localhost", auto_correct: true # fabric orderer service
  config.vm.network :forwarded_port, guest: 7051, host: 7051, id: "peer", host_ip: "localhost", auto_correct: true # fabric peer service
  config.vm.network :forwarded_port, guest: 7053, host: 7053, id: "peer_event", host_ip: "localhost", auto_correct: true # fabric peer event service
  config.vm.network :forwarded_port, guest: 7054, host: 7054, id: "ca", host_ip: "localhost", auto_correct: true # fabric-ca service
  config.vm.network :forwarded_port, guest: 5984, host: 15984, id: "couchdb", host_ip: "localhost", auto_correct: true # CouchDB service
  config.vm.network :forwarded_port, guest: 10000, host: 10000, id: "orderer_api", host_ip: "localhost", auto_correct: true # Orderer API
  config.vm.network :forwarded_port, guest: 30000, host: 30000, id: "subcontractor_api", host_ip: "localhost", auto_correct: true # Subcontractor API
  config.vm.network :forwarded_port, guest: 50000, host: 50000, id: "third_party_api", host_ip: "localhost", auto_correct: true # Third Party API
  config.vm.network :forwarded_port, guest: 8080, host: 8080, id: "orderer_frontend", host_ip: "localhost", auto_correct: true # Orderer frontend
  config.vm.network :forwarded_port, guest: 10080, host: 10080, id: "subcontractor_frontend", host_ip: "localhost", auto_correct: true # Subcontractor frontend
  config.vm.network :forwarded_port, guest: 12080, host: 12080, id: "third_party_frontend", host_ip: "localhost", auto_correct: true # Third Party frontend
  config.vm.provider :hyperv do |vb|
    vb.vmname = "hyperledger"
    vb.cpus = 2
    vb.maxmemory = 8192
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y build-essential
    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    apt-get install -y nodejs
    snap install docker
    sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
  SHELL
end